### ISSUE TITLE
Is it possible to receive an email?

### ISSUE THREAD

**Issue by mjohn123** [arpit999/SendMail#1]
Hello, Thank you for your work. I am making an application to block/reject email from some spam emails (given before). Hence, I want to catch all emails to my app, then compare them with a blacklist table. Is it possible to modify your code for my task? Thank you in advance

In addition, I was not successful to run your code. I got the error as

`07-29 20:35:59.109 26231-26261/com.tranetech.openspace.sendmail I/GMail: Email Message created.
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask: null
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask: javax.mail.AuthenticationFailedException
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask:     at javax.mail.Service.connect(Service.java:319)
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask:     at javax.mail.Service.connect(Service.java:169)
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask:     at com.tranetech.openspace.sendmail.GMail.sendEmail(GMail.java:78)
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask:     at com.tranetech.openspace.sendmail.SendMailTask.doInBackground(SendMailTask.java:39)
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-29 20:36:01.119 26231-26261/com.tranetech.openspace.sendmail E/SendMailTask:     at java.lang.Thread.run(Thread.java:818)
07-29 20:36:01.129 26231-26231/com.tranetech.openspace.sendmail D/AndroidRuntime: Shutting down VM
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime: FATAL EXCEPTION: main
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime: Process: com.tranetech.openspace.sendmail, PID: 26231
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime:     at com.tranetech.openspace.sendmail.SendMailTask.onProgressUpdate(SendMailTask.java:51)
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:648)
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145)
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5951)
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
07-29 20:36:01.139 26231-26231/com.tranetech.openspace.sendmail E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
`

**Comment by arpit999** [comment]
Not sure about that i need R&D and let you know if  it happend or not

**Comment by srd17palla** [comment]
Hello All,

I'm building an android application which needs to send an email verification code. For that I'm playing around this project(SendMail). But if failed to send email and I ran it on Android 5.1.1. I have attached logcat output below. Can somebody tell me whats the reason behind "**AuthenticationFailedException**"?
 Is it caused because of missing **dpmapi.jar**? or any security issues?

**Logcat Output:**
01-29 21:59:35.004 24122-24122/com.tranetech.openspace.sendmail D/RelationGraph: garbageCollect()
01-29 21:59:35.004 24122-24122/com.tranetech.openspace.sendmail D/ContextRelationManager: ContextRelationManager() : FEATURE_ENABLED=true
01-29 21:59:35.014 24122-24122/com.tranetech.openspace.sendmail W/ResourcesManager: getTopLevelResources: /data/app/com.tranetech.openspace.sendmail-1/base.apk / 1.0 running in com.tranetech.openspace.sendmail rsrc of package com.tranetech.openspace.sendmail
01-29 21:59:35.014 24122-24122/com.tranetech.openspace.sendmail I/InjectionManager: Inside getClassLibPath + mLibMap{0=, 1=}
01-29 21:59:35.024 24122-24122/com.tranetech.openspace.sendmail D/ResourcesManager: For user 0 new overlays fetched Null
01-29 21:59:35.024 24122-24122/com.tranetech.openspace.sendmail I/InjectionManager: Inside getClassLibPath caller 
01-29 21:59:35.034 24122-24122/com.tranetech.openspace.sendmail W/System: ClassLoader referenced unknown path: /data/app/com.tranetech.openspace.sendmail-1/lib/arm64
01-29 21:59:35.034 24122-24122/com.tranetech.openspace.sendmail I/InstantRun: Instant Run Runtime started. Android package is com.tranetech.openspace.sendmail, real application class is null.
01-29 21:59:35.044 24122-24122/com.tranetech.openspace.sendmail W/art: Failed to open zip archive '/system/framework/dpmapi.jar': I/O Error
01-29 21:59:35.444 24122-24122/com.tranetech.openspace.sendmail W/System: ClassLoader referenced unknown path: /data/app/com.tranetech.openspace.sendmail-1/lib/arm64
01-29 21:59:35.454 24122-24122/com.tranetech.openspace.sendmail D/InjectionManager: InjectionManager
01-29 21:59:35.454 24122-24122/com.tranetech.openspace.sendmail D/InjectionManager: fillFeatureStoreMap com.tranetech.openspace.sendmail
01-29 21:59:35.454 24122-24122/com.tranetech.openspace.sendmail I/InjectionManager: Constructor com.tranetech.openspace.sendmail, Feature store :{}
01-29 21:59:35.454 24122-24122/com.tranetech.openspace.sendmail I/InjectionManager: featureStore :{}
01-29 21:59:35.474 24122-24122/com.tranetech.openspace.sendmail W/ResourcesManager: getTopLevelResources: /data/app/com.tranetech.openspace.sendmail-1/base.apk / 1.0 running in com.tranetech.openspace.sendmail rsrc of package com.tranetech.openspace.sendmail
01-29 21:59:35.474 24122-24122/com.tranetech.openspace.sendmail D/RelationGraph: garbageCollect()
01-29 21:59:35.474 24122-24122/com.tranetech.openspace.sendmail W/ResourcesManager: getTopLevelResources: /data/app/com.tranetech.openspace.sendmail-1/base.apk / 1.0 running in com.tranetech.openspace.sendmail rsrc of package com.tranetech.openspace.sendmail
01-29 21:59:35.524 24122-24122/com.tranetech.openspace.sendmail D/Activity: performCreate Call Injection manager
01-29 21:59:35.534 24122-24122/com.tranetech.openspace.sendmail I/InjectionManager: dispatchOnViewCreated > Target : com.tranetech.openspace.sendmail.SendMailActivity isFragment :false
01-29 21:59:35.544 24122-24122/com.tranetech.openspace.sendmail D/SecWifiDisplayUtil: Metadata value : SecSettings2
01-29 21:59:35.544 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{34c3f5d I.E...... R.....ID 0,0-0,0}
01-29 21:59:35.544 24122-24206/com.tranetech.openspace.sendmail D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-29 21:59:35.604 24122-24206/com.tranetech.openspace.sendmail I/Adreno: QUALCOMM build                   : 0039a8c, I5bc0f577f9
                                                                          Build Date                       : 08/03/16
                                                                          OpenGL ES Shader Compiler Version: XE031.08.00.02
                                                                          Local Branch                     : 
                                                                          Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.HB.1.1.1.C1.06.00.00.165.223
                                                                          Remote Branch                    : NONE
                                                                          Reconstruct Branch               : NOTHING
01-29 21:59:35.614 24122-24206/com.tranetech.openspace.sendmail D/libEGL: eglInitialize EGLDisplay = 0x7f6b9bf188
01-29 21:59:35.614 24122-24206/com.tranetech.openspace.sendmail I/OpenGLRenderer: Initialized EGL, version 1.4
01-29 21:59:35.644 24122-24206/com.tranetech.openspace.sendmail D/libGLESv1: DTS_GLAPI : DTS is not allowed for Package : com.tranetech.openspace.sendmail
01-29 21:59:35.744 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
01-29 21:59:35.774 24122-24122/com.tranetech.openspace.sendmail I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@9b47212 time:137285246
01-29 21:59:36.044 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 1128) vi=Rect(0, 96 - 0, 1128) or=1
01-29 21:59:52.614 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-29 21:59:52.694 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-29 21:59:54.474 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-29 21:59:54.534 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-29 21:59:54.714 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 1000) vi=Rect(0, 96 - 0, 1000) or=1
01-29 21:59:55.344 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processKey 0
01-29 21:59:55.434 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processKey 1
01-29 22:00:02.924 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processKey 0
01-29 22:00:02.934 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processKey 1
01-29 22:00:05.364 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-29 22:00:05.404 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-29 22:00:05.494 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 1128) vi=Rect(0, 96 - 0, 1128) or=1
01-29 22:00:14.404 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-29 22:00:14.454 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-29 22:00:18.764 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: The input has been finished in ImeInputStage.
01-29 22:00:18.834 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: The input has been finished in ImeInputStage.
01-29 22:00:18.884 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
01-29 22:00:19.414 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-29 22:00:19.474 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-29 22:00:19.674 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 1128) vi=Rect(0, 96 - 0, 1128) or=1
01-29 22:00:21.264 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: The input has been finished in ImeInputStage.
01-29 22:00:21.334 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: The input has been finished in ImeInputStage.
01-29 22:00:21.364 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
01-29 22:00:22.594 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-29 22:00:22.664 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-29 22:00:22.674 24122-24122/com.tranetech.openspace.sendmail I/SendMailActivity: Send Button Clicked.
01-29 22:00:22.674 24122-24122/com.tranetech.openspace.sendmail I/SendMailActivity: To List: [ somebody@gmail.com]
01-29 22:00:22.724 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{5b9a2dd V.E...... R.....I. 0,0-0,0}
01-29 22:00:22.724 24122-26435/com.tranetech.openspace.sendmail I/SendMailTask: About to instantiate GMail...
01-29 22:00:22.734 24122-26435/com.tranetech.openspace.sendmail I/GMail: Mail server properties set.
                                                                         
                                                                         [ 01-29 22:00:22.744 24122:26435 W/         ]
                                                                         Unable to open '/system/framework/dpmapi.jar': No such file or directory
01-29 22:00:22.744 24122-26435/com.tranetech.openspace.sendmail W/art: Failed to open zip archive '/system/framework/dpmapi.jar': I/O Error
                                                                       
                                                                       [ 01-29 22:00:22.754 24122:26435 W/         ]
                                                                       Unable to open '/system/framework/dpmapi.jar': No such file or directory
01-29 22:00:22.754 24122-26435/com.tranetech.openspace.sendmail W/art: Failed to open zip archive '/system/framework/dpmapi.jar': I/O Error
                                                                       
                                                                       [ 01-29 22:00:22.754 24122:26435 W/         ]
                                                                       Unable to open '/system/framework/dpmapi.jar': No such file or directory
01-29 22:00:22.754 24122-26435/com.tranetech.openspace.sendmail W/art: Failed to open zip archive '/system/framework/dpmapi.jar': I/O Error
                                                                       
                                                                       [ 01-29 22:00:22.764 24122:26435 W/         ]
                                                                       Unable to open '/system/framework/dpmapi.jar': No such file or directory
01-29 22:00:22.764 24122-26435/com.tranetech.openspace.sendmail W/art: Failed to open zip archive '/system/framework/dpmapi.jar': I/O Error
                                                                       
                                                                       [ 01-29 22:00:22.764 24122:26435 W/         ]
                                                                       Unable to open '/system/framework/dpmapi.jar': No such file or directory
01-29 22:00:22.764 24122-26435/com.tranetech.openspace.sendmail W/art: Failed to open zip archive '/system/framework/dpmapi.jar': I/O Error
                                                                       
                                                                       [ 01-29 22:00:22.774 24122:26435 W/         ]
                                                                       Unable to open '/system/framework/dpmapi.jar': No such file or directory
01-29 22:00:22.774 24122-26435/com.tranetech.openspace.sendmail W/art: Failed to open zip archive '/system/framework/dpmapi.jar': I/O Error
                                                                       
                                                                       [ 01-29 22:00:22.784 24122:26435 W/         ]
                                                                       Unable to open '/system/framework/dpmapi.jar': No such file or directory
01-29 22:00:22.784 24122-26435/com.tranetech.openspace.sendmail W/art: Failed to open zip archive '/system/framework/dpmapi.jar': I/O Error
01-29 22:00:22.784 24122-26435/com.tranetech.openspace.sendmail I/GMail: toEmail: sridhar.java.android@gmail.com
01-29 22:00:22.794 24122-26435/com.tranetech.openspace.sendmail I/GMail: Email Message created.
01-29 22:00:22.864 24122-24122/com.tranetech.openspace.sendmail D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
javax.mail.AuthenticationFailedException
 at javax.mail.Service.connect(Service.java:319)
 at javax.mail.Service.connect(Service.java:169)
 at com.tranetech.openspace.sendmail.GMail.sendEmail(GMail.java:78)
 at com.tranetech.openspace.sendmail.SendMailTask.doInBackground(SendMailTask.java:39)
 at android.os.AsyncTask$2.call(AsyncTask.java:295)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 at java.lang.Thread.run(Thread.java:818)

**Comment by arpit999** [comment]
You have to enable one option less secure in your account which you use for
email.

**Comment by srd17palla** [comment]
**Update about the AuthenticationFailedException** thing mentioned above. I got a message from Gmail says that it blocked "SendMail" app because of security issues. I disabled Security for my gmail account for a while and tried it. Then it worked fine. **Thank you for your work Arpit999**. This is awesome project.

**Comment by arpit999** [comment]
Anytime

On 31 Jan 2017 03:03, "srd17palla" <notifications@github.com> wrote:

*Update about the AuthenticationFailedException* thing mentioned above. I
got a message from Gmail says that it blocked "SendMail" app because of
security issues. I disabled for a while and tried it. This project worked
fine. Thank you for your work Arpit999. This is awesome project.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/arpit999/SendMail/issues/1#issuecomment-276198019>, or mute
the thread
